spring:
  application:
    name: store_api
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Pas123456@
  jpa:
    show-sql: true
  flyway:
    enabled: false
server:
  port: 9090